"""create_door_table

Revision ID: 2a1a5e3776b6
Revises: 57b2ec0178b4
Create Date: 2026-05-12 16:02:09.400668

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlmodel.sql.sqltypes import AutoString


# revision identifiers, used by Alembic.
revision: str = "2a1a5e3776b6"
down_revision: Union[str, Sequence[str], None] = "57b2ec0178b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "door",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", AutoString(length=128), nullable=False),
        sa.Column("location", AutoString(length=256), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_door_name"), "door", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_door_name"), table_name="door")
    op.drop_table("door")
    # ### end Alembic commands ###
