"""add_face_vector_table_remove_face_embedding

Revision ID: 57b2ec0178b4
Revises: 159a5b93267b
Create Date: 2026-05-11 16:10:38.223891

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlmodel.sql.sqltypes import AutoString


# revision identifiers, used by Alembic.
revision: str = "57b2ec0178b4"
down_revision: Union[str, Sequence[str], None] = "159a5b93267b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "facevector",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("embedding", sa.LargeBinary(), nullable=False),
        sa.Column("label", AutoString(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_facevector_user_id"), "facevector", ["user_id"], unique=False
    )
    with op.batch_alter_table("user") as batch_op:
        batch_op.drop_column("face_embedding")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user") as batch_op:
        batch_op.add_column(sa.Column("face_embedding", sa.BLOB(), nullable=True))
    op.drop_index(op.f("ix_facevector_user_id"), table_name="facevector")
    op.drop_table("facevector")
    # ### end Alembic commands ###
